# Generated by Django 4.0.3 on 2023-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0008_alter_project_github_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='used_technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='cms',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_backend_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_frontend_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='language_used',
            field=models.CharField(default='Python & Javascript', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='library_used',
            field=models.CharField(default='React & Django', max_length=1000),
        ),
    ]
