# Generated by Django 4.0.3 on 2023-12-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0009_remove_project_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language_used',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='library_used',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
