# Generated by Django 4.0.3 on 2023-12-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_id_adress', models.CharField(max_length=200, null=True)),
                ('visit_timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(null=True)),
                ('website_accessed', models.CharField(max_length=200)),
            ],
        ),
    ]
