# Generated by Django 4.0.3 on 2023-12-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0002_alter_chatbotdata_email_alter_chatbotdata_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotdata',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10, null=True),
        ),
    ]
